version: "3.9"
services:
  db-bank:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test1234
    ports:
      - 5433:5432
    volumes:
      - bank-pg-data:/var/lib/postgresql/data
volumes:
  bank-pg-data: